// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://puhvxlnmjlvdxnfbogrt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB1aHZ4bG5tamx2ZHhuZmJvZ3J0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgwNDA3NTUsImV4cCI6MjA1MzYxNjc1NX0.72RqDHnJGsGhRXW_S0qsakY5QWW14OtBX3Z9mOWXMGg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);